"""Add farmer_notes and total_amount to Order

Revision ID: 49345f3a3741
Revises: 8f81520c06c6
Create Date: 2025-07-21 22:47:18.800049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49345f3a3741'
down_revision = '8f81520c06c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('farmer_notes')

    # ### end Alembic commands ###
