"""fix order fields

Revision ID: 8c1129aff71c
Revises: b535e666df60
Create Date: 2025-07-23 18:19:53.768403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1129aff71c'
down_revision = 'b535e666df60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
