"""Add OrderItem model and update Order/Animal

Revision ID: 7825f40a44cf
Revises: d10c4804e356
Create Date: 2025-07-23 23:13:05.391813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7825f40a44cf'
down_revision = 'd10c4804e356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('farmer_notes', sa.Text(), nullable=True))
        batch_op.drop_column('animal_type')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('animal_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('farmer_notes')
        batch_op.drop_column('status')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
